[package]
name = "retrieve-state"
version = "0.1.0"
authors = ["Daniel Werner <dan@casperlabs.io>"]
edition = "2018"

[dependencies]
anyhow = "1"
casper-contract = { path = "../../smart_contracts/contract", default-features = false, features = ["std"] }
casper-execution-engine = { path = "../../execution_engine" }
casper-hashing = { path = "../../hashing" }
casper-node = { path = "../../node" }
casper-types = { path = "../../types", default-features = false, features = ["std"] }
hex = "0.4.3"
jsonrpc-lite = "0.5.0"
lmdb = "0.8.0"
reqwest = { version = "0.11.1", features = ["json", "gzip"] }
serde = "1"
serde_json = "1"
structopt = "0.3.22"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
walkdir = "2"
