[package]
name = "named-purse-payment"
version = "0.1.0"
authors = ["Ed Hastings <ed@gmail.com>"]
edition = "2018"

[[bin]]
name = "named_purse_payment"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
