[package]
name = "control-management"
version = "0.1.0"
authors = ["MichaÅ‚ Papierski <michal@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "control_management"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
