[package]
name = "transfer-to-existing-account"
version = "0.1.0"
authors = ["Micha≈Ç Papierski <michal@papierski.net>"]
edition = "2018"

[[bin]]
name = "transfer_to_existing_account"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["contract/std", "types/std"]

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../../types", package = "casperlabs-types" }
