[package]
name = "casperlabs-types"
version = "0.6.0" # when updating, also update 'html_root_url' in lib.rs
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"
description = "Types used to allow creation of Wasm contracts and tests for use on the CasperLabs network."
readme = "README.md"
documentation = "https://docs.rs/casperlabs-types"
homepage = "https://casperlabs.io"
repository = "https://github.com/CasperLabs/CasperLabs/tree/master/execution-engine/types"
license-file = "../../LICENSE"

[dependencies]
base16 = { version = "0.2.1", default-features = false }
bitflags = "1"
blake2 = { version = "0.8.1", default-features = false }
# TODO: Replace failure with thiserror once no_std support is landed https://github.com/dtolnay/thiserror/pull/64
failure = { version = "0.1.6", default-features = false, features = ["failure_derive"] }
hex_fmt = "0.3.0"
num-derive = { version = "0.3.0", default-features = false }
num-integer = { version = "0.1.42", default-features = false }
num-traits = { version = "0.2.10", default-features = false }
proptest = { version = "0.10.0", optional = true }
serde = { version = "1", default-features = false, features = ["derive"] }
uint = { version = "0.8.3", default-features = false }

[dev-dependencies]
criterion = "0.3.3"
proptest = "0.10.0"
version-sync = "0.8"

[features]
default = ["base16/alloc", "serde/alloc"]
std = ["base16/std"]
gens = ["std", "proptest/std"]
no-unstable-features = []

[[bench]]
name = "bytesrepr_bench"
harness = false

[package.metadata.docs.rs]
features = ["no-unstable-features"]

