[package]
name = "casper-engine-grpc-server"
version = "0.6.3"
authors = ["Mateusz GÃ³rski <gorski.mateusz@protonmail.ch>"]
edition = "2018"
description = "Wasm execution engine for Casper smart contracts."
readme = "README.md"
documentation = "https://docs.rs/casper-engine-grpc-server"
homepage = "https://casperlabs.io"
repository = "https://github.com/CasperLabs/casper-node/tree/master/grpc/server"
# this is required by 'cargo rpm'
license-file = "../../LICENSE"
include = [
    "**/*.rs",
    "Cargo.toml",
    "protobuf/io/casperlabs/casper/consensus/state.proto",
    "protobuf/io/casperlabs/ipc/ipc.proto",
    "protobuf/io/casperlabs/ipc/transforms.proto",
]

[dependencies]
casper-execution-engine = { version = "0.6.3", path = "../../execution_engine", features = ["gens"] }
casper-types = { version = "0.6.3", path = "../../types", features = ["std", "gens"] }
clap = "2"
ctrlc = "3"
dirs = "3"
grpc = "0.6.1"
lmdb = "0.8"
log = "0.4.8"
protobuf = "=2.8"
datasize = "0.2.0"
num = { version = "0.3.0", default-features = false }
num-rational = "0.3.0" 

[build-dependencies]
protoc-rust-grpc = "0.6.1"

[dev-dependencies]
parity-wasm = "0.42.1"
proptest = "0.10.0"
rand = "0.7.2"

[features]
test-support = ["casper-execution-engine/test-support"]

[[bin]]
name = "casper-engine-grpc-server"
path = "src/main.rs"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
casper-engine-grpc-server = { path = "/usr/bin/casper-engine-grpc-server" }

[package.metadata.rpm.files]
"../packaging/casper-engine-grpc-server.service" = { path = "/lib/systemd/system/casper-engine-grpc-server.service" }

[package.metadata.deb]
maintainer-scripts="debian"
assets = [
	["packaging/casper-engine-grpc-server.service", "/lib/systemd/system/casper-engine-grpc-server.service", "644"],
	["../../target/release/casper-engine-grpc-server", "/usr/bin/casper-engine-grpc-server", "755"]
]
extended-description = """
Wasm execution engine for Casper smart contracts.

For information on using package, see https://github.com/CasperLabs/casper-node
"""

