[package]
name = "withdraw-bid"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "withdraw_bid"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
