[package]
name = "highway-state-grapher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1"
clap = { version = "4", features = ["derive"] }
casper-hashing = { path = "../../hashing" }
casper-node = { path = "../../node" }
casper-types = { path = "../../types" }
flate2 = "1"
freetype-sys = "0.13"
glium = "0.26"
glium_text_rusttype = "0.3"
libc = "0.2"
nalgebra = "0.32"
serde = "1"
