[package]
name = "transfer-to-account-u512"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "transfer_to_account_u512"
path = "src/bin/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["contract/std", "types/std"]

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../../types", package = "casperlabs-types" }
