[package]
name = "create-accounts"
version = "0.1.0"
authors = ["MichaÅ‚ Papierski <michal@papierski.net>"]
edition = "2018"

[[bin]]
name = "create_accounts"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casperlabs-contract/std", "casperlabs-types/std"]

[dependencies]
casperlabs-contract = { path = "../../../contract" }
casperlabs-types = { path = "../../../../types" }
