[package]
name = "faucet-stored"
version = "0.1.0"
authors = ["Mateusz GÃ³rski <mateusz@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "faucet_stored"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = { path = "../../../contract" }
faucet = { path = "../faucet" }
casper-types = { path = "../../../../types" }