[package]
name = "faucet-stored"
version = "0.1.0"
authors = ["Mateusz GÃ³rski <mateusz@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "faucet_stored"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casperlabs-contract/std", "casperlabs-types/std"]

[dependencies]
casperlabs-contract = { path = "../../../contract" }
faucet = { path = "../faucet" }
casperlabs-types = { path = "../../../../types" }
