[package]
name = "global-state-update-gen"
version = "0.2.0"
authors = ["Bartłomiej Kamiński <bart@casperlabs.io>"]
edition = "2018"

[dependencies]
base16 = "0.2.1"
base64 = "0.13"
casper-engine-test-support = { path = "../../execution_engine_testing/test_support" }
casper-execution-engine = { path = "../../execution_engine" }
casper-hashing = { path = "../../hashing" }
casper-types = { path = "../../types" }
clap = "2.33"
lmdb = "0.8"
rand = "0.8"
