[package]
name = "auction"
version = "0.1.0"
authors = ["MichaÅ‚ Papierski <michal@papierski.net>"]
edition = "2018"

[lib]
bench = false
doctest = false
test = false

[features]
std = ["contract/std", "types/std"]

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../../types", package = "casperlabs-types" }
