[package]
name = "casper-contract"
version = "1.4.4" # when updating, also update 'html_root_url' in lib.rs
authors = ["Michael Birch <birchmd@casperlabs.io>", "Mateusz GÃ³rski <gorski.mateusz@protonmail.ch>"]
edition = "2018"
description = "A library for developing Casper network smart contracts."
readme = "README.md"
documentation = "https://docs.rs/casper-contract"
homepage = "https://casperlabs.io"
repository = "https://github.com/CasperLabs/casper-node/tree/master/smart_contracts/contract"
license = "Apache-2.0"

[dependencies]
casper-types = { version = "1.5.0", path = "../../types" }
hex_fmt = "0.3.0"
version-sync = { version = "0.9", optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[features]
default = ["no-std-helpers"]
no-std-helpers = ["wee_alloc"]
test-support = []
# DEPRECATED - enabling `std` has no effect.
std = []
