[package]
name = "casper-contract"
version = "0.7.7" # when updating, also update 'html_root_url' in lib.rs
authors = ["Michael Birch <birchmd@casperlabs.io>", "Mateusz GÃ³rski <gorski.mateusz@protonmail.ch>"]
edition = "2018"
description = "Library for developing Casper smart contracts."
readme = "README.md"
documentation = "https://docs.rs/casper-contract"
homepage = "https://casperlabs.io"
repository = "https://github.com/CasperLabs/casper-node/tree/master/smart_contracts/contract"
license-file = "../../LICENSE"

[dependencies]
casper-types = { version = "0.7.7", path = "../../types" }
hex_fmt = "0.3.0"
thiserror = "1.0.18"
version-sync = { version = "0.9", optional = true }
wee_alloc = "0.4.5"

[features]
default = []
std = ["casper-types/std", "version-sync"]
test-support = []
