[package]
name = "auction-install"
version = "0.1.0"
authors = ["Micha≈Ç Papierski <michal@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "auction_install"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casper-contract/std", "casper-types/std"]

[dependencies]
auction = { path = "../auction" }
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
