[package]
name = "transfer-to-purse"
version = "0.1.0"
authors = ["MichaÅ‚ Papierski <michal@papierski.net>"]
edition = "2018"

[[bin]]
name = "transfer_to_purse"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
