[package]
name = "redelegate"
version = "0.1.0"
authors = ["Karan Dhareshwar <karan@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "redelegate"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
