[package]
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
description = "A tool to update versions of all published CasperLabs packages."
edition = "2018"
license-file = "../../LICENSE"
name = "casper-updater"
readme = "README.md"
version = "0.2.0"

[dependencies]
casper-types = { version = "1.0.0", path = "../../types", features = ["std"] }
clap = "2"
once_cell = "1"
regex = "1"
