[package]
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
description = "A tool to update versions of all published CasperLabs packages."
edition = "2018"
license-file = "../../LICENSE"
name = "casper-updater"
readme = "README.md"
version = "0.2.0"

[dependencies]
clap = "2"
once_cell = "1.5.2"
regex = "1"
casper-types = { version = "0.9.3", path = "../../types", features = ["std"] }