[package]
name = "standard-payment-install"
version = "0.1.0"
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "standard_payment_install"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["casper-contract/std", "casper-types/std"]

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
standard-payment = { path = "../standard-payment" }
