[package]
name = "casper-validation"
version = "0.1.0"
authors = ["MichaÅ‚ Papierski <michal@casperlabs.io>"]
edition = "2018"

[dependencies]
anyhow = "1"
base16 = "0.2.1"
casper-types = { path = "../../types" }
clap = { version ="3.0.0-rc.0", features = ["derive"] }
derive_more = "0.99.13"
hex = { version = "0.4.2", features = ["serde"] }
serde = "1"
serde_json = "1"
thiserror = "1.0.18"

[[test]]
name = "validation_test"
harness = false

[[bin]]
name = "casper-validation"
test = false
doctest = false

[lib]
test = false
doctest = false
