[package]
name = "faucet"
version = "0.1.0"
authors = ["Mateusz GÃ³rski <mateusz@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "faucet"
path = "src/bin/main.rs"
doctest = false
test = false
bench = false

[features]
std = ["casperlabs-contract/std", "casperlabs-types/std"]

[dependencies]
casperlabs-contract = { path = "../../../contract" }
casperlabs-types = { path = "../../../../types" }
