[package]
name = "faucet"
version = "0.1.0"
authors = ["Mateusz GÃ³rski <mateusz@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "faucet"
path = "src/bin/main.rs"
doctest = false
test = false
bench = false

[features]
std = ["casper-contract/std", "casper-types/std"]

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
